name: Build ETL Component from Ab Initio Graphs (Gradle)

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # - name: Debug list build directory
      #   run: |
      #       pwd
      #       ls -l
      #       ls -l build
      #       ls -l build/generate_component.sh        

      - name: Generate Gradle Wrapper
        run: |
          gradle wrapper --gradle-version 8.6

      - name: Commit Gradle Wrapper (if needed)
        run: |
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add gradlew gradlew.bat gradle/
            if git diff --cached --quiet; then
              echo "No changes to commit"
            else
              git commit -m "Add Gradle Wrapper"
              git push
            fi        

      # 3️⃣ Login to Docker Hub (needed before push)
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
            -u ${{ secrets.DOCKERHUB_USERNAME }} \
            --password-stdin

      # 4️⃣ Build ETL component, TAR, and OCI image using Gradle
      - name: Build using Gradle
        run: |
          ./gradlew clean packageTar buildDockerImage pushDockerImage

      - name: Tag and push image
        run: |
                        docker tag etl-component-build-gradle:${{ github.ref_name }} \
                          ${{ secrets.DOCKERHUB_USERNAME }}/etl-component:${{ github.ref_name }}
                    
                        docker push ${{ secrets.DOCKERHUB_USERNAME }}/etl-component-build-gradle:${{ github.ref_name }}

      # 5️⃣ Upload TAR artifact (for visibility)
      - name: Upload TAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: etl-component-build-gradle-tar
          path: build/artifacts/*.tar.gz