name: Build ETL Component from Ab Initio Graphs (Gradle – Actions Only)

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # 1️⃣ Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Java + Gradle cache
      - name: Setup Java 17 with Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # 3️⃣ Verify Gradle Wrapper
      - name: Verify Gradle
        run: ./gradlew --version

      # 4️⃣ Build ETL component + TAR (Gradle is the build tool)
      - name: Build ETL component using Gradle
        run: |
          ./gradlew clean packageTar

      - name: Sonarqube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonar \
            -Dsonar.projectKey=github_actions_workflow_abinitio_etl-component-gradle \
            -Dsonar.login=$SONAR_TOKEN

      # 5️⃣ Upload TAR artifact
      - name: Upload ETL TAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: etl-component-gradle-tar
          path: build/artifacts/*.tar.gz

      # 6️⃣ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 7️⃣ Build & Push OCI Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/etl-component:graph-user-flow-v1.1.1

      - name: Save image as Tar
        run: |
          docker save ${{ secrets.DOCKERHUB_USERNAME }}/etl-component:graph-user-flow-v1.1.1 -o build/artifacts/etl-component-image.tar

      # Build & Push enrichment image
      - name: Build & Push Enrichment Component Image
        uses: docker/build-push-action@v5
        with:
          context: enrich-component
          file: enrich-component/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/enrich-component:v1

      - name: Ensure pipeline script is executable
        run: chmod +x runtime/master_pipeline.sh          

      - name: Run Master Pipeline
        run: |
              ./runtime/master_pipeline.sh